# Site settings
title: Laura Wilson
author: 
  name: Laura Wilson
  job: Web Developer
  other_job: Blogger
  subtitle: Available to speak at events
  bio: I'm a woman in tech, sometimes Codebar coach, and lover of good coffee
  avatar: /assets/profile.png
email: ""
google_analytics: UA-99146516-1
form_submission: https://getsimpleform.com/messages?form_api_token=2c85eaa958ba3e9c062f715f5c24ea0f
description: Laura Wilson - Web Developer. Portfolio and Blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lsewilson.github.io" # the base hostname & protocol for your site
twitter_username: wilslau
github_username:  lsewilson
linkedin_username: laurasewilson
instagram_username: laurasewilson

# Build settings
markdown: kramdown
permalink: pretty
post_dirs: false
paginate: 5
paginate_path: /blog/page/:num     
gems:
  - jekyll-paginate