# Site settings
title: Laura Wilson
author: 
  name: Laura Wilson
  job: Web Developer 
  other_job: Blogger
  current_employer: Movebubble
  bio: I'm a woman in tech, sometimes Codebar coach, and lover of good coffee
  avatar: /assets/profile.png
email: ""
description: Laura Wilson - Web Developer. Portfolio and Blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lsewilson.github.io" # the base hostname & protocol for your site
twitter_username: wilslau
github_username:  lsewilson
linkedin_username: laurasewilson
instagram_username: laurasewilson

# Build settings
markdown: kramdown
permalink: pretty
post_dirs: false
paginate: 5
paginate_path: /blog/page/:num     
gems:
  - jekyll-paginate